Updated to match latest

diff --git a/.github/workflows/serverless_pr.yaml b/.github/workflows/serverless_pr.yaml
--- a/.github/workflows/serverless_pr.yaml
+++ b/.github/workflows/serverless_pr.yaml
@@ -2,6 +2,7 @@ name: Serverless PR
 on:
   pull_request:
     branches:
+      # This is the name of the primary branch, which may be `main` for newer repos.
       - main
 
 env:
@@ -13,35 +14,57 @@ jobs:
     runs-on: ubuntu-latest
     name: Serverless PR handler
     outputs:
-      # Add extra outputs to correspond to any additions to the matched patterns in the filter step below.
-      distributor: ${{ steps.filter.outputs.distributor }}
+      # Add extra outputs here to match any additions to the matched patterns in the filter step below.
+      distributor_incoming: ${{ steps.filter.outputs.distributor_incoming }}
     steps:
-      - name: Match files in PR against rules
+      - name: Check for changed files
         id: filter
         uses: dorny/paths-filter@v2
         with:
           list-files: shell
-          # Can add more patterns here if necessary, don't forget to update the outputs above if you do so!
           filters: |
-            distributor:
-              - '${{ env.DISTRIBUTOR_ROOT }}/logs/*/incoming/*'
+            distributor_incoming:
+              - added: '${{ env.DISTRIBUTOR_ROOT }}/logs/*/incoming/*'
+            distributor_private:
+              - '${{ env.DISTRIBUTOR_ROOT }}!(/logs/*/incoming/*)'
 
-# This job does a more detailed check on the contents of any incoming checkpoints added.
-# Run this job only when we've detected a witnessed checkpoint
-  distributor_pr_validator:
+      - name: Detect distributor structure changes
+        if: steps.filter.outputs.distributor_private == 'true'
+        run: |
+          for i in ${{ steps.filter.outputs.distributor_private_files }}; do
+            echo "::error file=${i}::Modified protected distributor structure"
+          done
+          exit 1
+
+# Run this job only when we've detected a distributor checkpoint PR
+  distributor_validator:
     needs: changes
-    if: ${{ needs.changes.outputs.distributor == 'true' }}
+    if: ${{ needs.changes.outputs.distributor_incoming == 'true' }}
     runs-on: ubuntu-latest
-    name: Handle witness PR
+    name: Handle distributor PR
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
           ref: "refs/pull/${{ github.event.number }}/merge"
-      - name: Validate distributor PR
-        uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@master
+      - name: Combine witness signatures (dry run)
+        id: combine_witness_signatures_dry_run
+        uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@HEAD
         with:
-          distributor_dir: '${{ env.DISTRIBUTOR_ROOT }}'
-          config: '${{ env.DISTRIBUTOR_ROOT }}/config.yaml'
-          dry_run: true
+            distributor_dir: './distributor'
+            config: './distributor/config.yaml'
+            dry_run: true
+      # OPTIONAL: Store PR number (only needed if we're using the automerge action below)
+      - id: save_metadata
+        name: Save PR number
+        run: |
+          D=$(mktemp -d)/pr_metadata
+          mkdir -p ${D}
+          echo ${{ github.event.number }} > ${D}/NR
+          echo "::set-output name=metadata_dir::${D}"
+      - uses: actions/upload-artifact@v2
+        with:
+          name: pr_metadata
+          path: ${{ steps.save_metadata.outputs.metadata_dir }}
+      # End OPTIONAL.
 
